version: '3'

networks:
  lumen:

services:

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8082:80"
    volumes:
      # linking src to www for easier editing of the files
      - ./src:/var/www
      # linking nginx conf from local directory to container
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql
    networks:
      - lumen

  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      # TODO: Remove environment passwords on prod.
      MYSQL_DATABASE: protein_tracker
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - lumen

  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    networks:
      - lumen


